Trading/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('transactions.urls')),
]

transactions/urls.py
from django.urls import path
from . import views


app_name = 'transactions'

urlpatterns = [
    path('buy/', views.buy, name='buy'),
    path('sell/', views.sell, name='sell'),
    path('<str:ticker>/', views.confirm, name='confirm'),
]

transactions/models.py
from codecs import backslashreplace_errors
from operator import mod
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Stock(models.Model):
    ticker = models.CharField(max_length=20)
    name = models.CharField(max_length=300)

    def __str__(self) -> str:
        return f'{self.ticker} {self.name}'

class Asset(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)
    stock = models.ForeignKey(Stock, related_name='stock', on_delete=models.CASCADE)
    quantity = models.FloatField()
    price = models.FloatField(verbose_name='Price per stock')
    sum = models.FloatField(default=0)

    def __str__(self) -> str:
        return f'{self.stock.ticker} {self.quantity} {self.price}'


class Balance(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.CASCADE, related_name='balance')
    total = models.FloatField(default=10000)

    def __str__(self) -> str:
        return f'{self.user.username} {self.total}'

transactions/forms.py
from typing import Any, Mapping, Optional, Union
from django import forms
from .models import Balance, Stock


class BuyConfirmForm(forms.Form):
    quantity = forms.FloatField(required=True)

    def clean_quantity(self):
        quantity = self.cleaned_data.get('qunatity')
        if not quantity:
            raise forms.ValidationError('Quantity must not be empty.')
        return quantity


class SearchForm(forms.Form):
    ticker = forms.CharField(max_length=10, required=False, widget=forms.TextInput(attrs={'style':'text-transform: uppercase;', 'class':'my-1'}))
    name = forms.CharField(max_length=100,required=False, widget=forms.TextInput(attrs={'class':'my-1'}))

    def clean(self):
        super().clean()
        ticker = self.cleaned_data.get('ticker')
        name = self.cleaned_data.get('name')
        if not ticker and not name:
            raise forms.ValidationError('Atleast one should not be empty.')


class ConfirmForm(forms.Form):
    quantity = forms.IntegerField(required=True, error_messages={'required':'Quantity must not be empty.'}, widget=forms.NumberInput())

transactions/views.py
from importlib import import_module

from django.http import HttpResponse
from .models import Balance, Stock
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render
from .forms import ConfirmForm, SearchForm
from .apis import request as api_request

# Create your views here.


@login_required
def buy(request):
    if request.method == 'POST':
        form = SearchForm(request.POST)
        stocks = Stock.objects.all()
        if form.is_valid():
            ticker = form.cleaned_data.get('ticker').upper()
            name = form.cleaned_data.get('name')
            if ticker and name:
                stocks = Stock.objects.filter(
                    ticker__contains=ticker, name__icontains=name)
            elif not ticker:
                stocks = Stock.objects.filter(name__icontains=name)
            elif not name:
                stocks = Stock.objects.filter(ticker__contains=ticker)
    else:
        stocks = Stock.objects.all()
        form = SearchForm()
    return render(request, 'transactions/buy.html', {'stocks': stocks, 'form': form})


@login_required
def sell(request):
    return render(request, 'transactions/sell.html')


@login_required
def confirm(request, ticker):
    if request.method == 'POST':
        print(request.POST)
        form = ConfirmForm(request.POST)
        data = api_request.get_price(ticker, '2020-10-14')
        stock = Stock.objects.get(ticker=ticker)
        if data['status'] != 'NOT_FOUND':
            max = Balance.objects.get(
                user=request.user).total / float(data['high'])
            min = max / 100
        else:
            max = 1
            min = 0.1
        if form.is_valid():
            return HttpResponse('Success')
        pass

    else:
        data = api_request.get_price(ticker, '2020-10-14')
        stock = Stock.objects.get(ticker=ticker)
        if data['status'] != 'NOT_FOUND':
            max = Balance.objects.get(
                user=request.user).total / float(data['high'])
            min = max / 100
        else:
            max = 1
            min = 0.1
        form = ConfirmForm()
    return render(request, 'transactions/confirm.html', {'data': data, 'form': form, 'stock': stock, 'max': round(max, 2), 'min': round(min, 3)},)

transactions/templates/transactions/buy.html
{% extends 'accounts/layout.html' %}
{% block static %}
{% load static %}
<link rel="stylesheet" href="{% static 'transactions/style.css' %}">
{% endblock %}
{% block body %}
<div class="col-12">
    <form method="POST">
        {% csrf_token %}
        {% load crispy_forms_tags %}
        {{ form|crispy }}
        <div class="text-center my-2">
            <button type="submit" class="btn btn-outline-success">Search</button>
        </div>
    </form>
</div>
<div class="alert alert-secondary text-center">
    <p class="my-auto">Account Balance: <span style="color: green;">${{ request.user.balance.all.0.total }}</span></p>
</div>
<div class="row">
    {% for stock in stocks %}
    <div class="col-sm-4 my-3">
        <div class="card text-center">
            <div class="card-body">
                <div class="card-title">{{ stock.ticker }}</div>
                <div class="card-text">{{ stock.name }}</div>
                <a href="{% url 'transactions:confirm' stock.ticker %}" class="btn btn-success my-2">Buy</a>
            </div>
        </div>
    </div>
    {% empty %}
    <div class="text-center col">
        <h4>No companies under your query.</h4>
        <a href="{% url 'transactions:buy' %}">Show all</a>
    </div>
    {% endfor %}
</div>
{% endblock %}

transactions/templates/transactions/confirm.html
{% extends 'accounts/layout.html' %}
{% block body %}
<div class="col">
    <div class="card text-center">
        <div class="card-body">
            {% if data.status != "NOT_FOUND" %}
            <p class="card-title">{{ stock.name }}</p>
            <p class="card-text">Price: <span style="color: green;">${{ data.high }}</span></p>
            <p class="card-text" style="color: green;">Quantity should be less than or equal to {{ max }}.</p>
            <form class="container" action="{% url 'transactions:confirm' data.symbol %}" method="POST">
                {% csrf_token %}
                {% load crispy_forms_tags %}
                {{ form|crispy }}
                <div class="my-2 text-center">
                    <button type="submit" class="btn btn-outline-success">Buy</button>
                </div>
            </form>
            {% else %}
            <h3 class="text-center alert alert-danger">Not found in polygon.io</h3>
            <a href="{% url 'transactions:buy' %}" class="btn btn-success">All stocks.</a>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

transactions/templates/transactions/sell.html
{% extends 'accounts/layout.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col">
            <h1 class="text-center">Sell Page</h1>
        </div>
    </div>
</div>
{% endblock %}