Trading/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('transactions.urls')),
]

accounts/urls.py
from unicodedata import name
from django.urls import path
from . import views


app_name = 'accounts'



urlpatterns = [
    path('', views.home, name='home'),
    path('signup/', views.signup, name='signup'),
    path('signin/', views.signin, name='signin'),
    path('signout/', views.signout, name='signout'),
]

transactions/urls.py
from django.urls import path
from . import views


app_name = 'transactions'

urlpatterns = [
    path('buy/', views.buy, name='buy'),
    path('sell/', views.sell, name='sell'),
    path('<str:ticker>/', views.confirm, name='confirm'),
]

accounts/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from tkinter import Widget
from turtle import width
from django.contrib.auth.models import User
from django import forms
from django.contrib.auth.forms import UserCreationForm


class SignupForm(UserCreationForm):
    def __init__(self, *args,  **kwargs) -> None:
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs = {
            'autofocus': False, 'class': 'my-1', }
        self.fields['password2'].label = 'Confirm Password'
        self.fields['email'].widget.attrs = {
            'class': 'validate my-1', 'required': '', }
        self.fields['email'].unique = True
        self.fields['first_name'].widget.attrs = {
            'required': '', 'class': 'my-3', 'autofocus': True}
        self.fields['last_name'].widget.attrs = {
            'required': '', 'class': 'my-3', }
        self.fields['password1'].widget.attrs = {
            'required': '', 'class': 'my-3', }
        self.fields['password2'].widget.attrs = {
            'required': '', 'class': 'my-3', }

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username',
                  'email', 'password1', 'password2']

    def clean_email(self):
        email = self.cleaned_data.get('email')
        users = User.objects.filter(email=email)
        if len(users) > 0:
            raise forms.ValidationError('Email already exists.')
        if not email:
            raise forms.ValidationError('Email must not be empty.')
        return email

    def clean_first_name(self):
        first_name = self.cleaned_data.get('first_name')
        if not first_name:
            raise forms.ValidationError('Firstname must not be empty.')
        return first_name

    def clean_last_name(self):
        last_name = self.cleaned_data.get('last_name')
        if not last_name:
            raise forms.ValidationError('Firstname must not be empty.')
        return last_name


class SigninForm(forms.Form):
    username = forms.CharField(required=True, max_length=150, widget=forms.TextInput(
        attrs={'class': 'my-3', 'autocomplete':'off'}), error_messages={'required': 'Username must not be empty.'},)
    password = forms.CharField(max_length=255, widget=forms.PasswordInput(
        attrs={'class': 'my-3', 'autocomplete':'off'}), error_messages={'required': 'Password must not be empty.'})

accounts/views.py
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.models import AnonymousUser
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import Group, User
from django.urls import reverse
from django.shortcuts import redirect, render
from django.contrib import messages
from transactions.models import Balance
from .forms import SigninForm, SignupForm

# Create your views here.


@login_required
def home(request):
    return render(request, 'accounts/home.html')


def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            user = User.objects.get(username=form.cleaned_data.get('username'))
            group = Group.objects.get(name='Users')
            user.groups.add(group,)
            Balance.objects.create(user=user).save()
            return HttpResponseRedirect(reverse('accounts:signin'))
    else:
        form = SignupForm()

    return render(request, 'accounts/signup.html', {'form': form})


def signin(request):
    if request.method == 'POST':
        form = SigninForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            try:
                user = authenticate(username=username, password=password)
                if user:
                    login(request, user)
                    return redirect('accounts:home')
                messages.error(request, 'Password is wrong.', 'danger')

            except User.DoesNotExist:
                messages.error(request, 'No such user', 'danger')
    else:
        messages.warning(request, 'You must sign in to continue!', 'warning')
        form = SigninForm()
    return render(request, 'accounts/signin.html', {'form': form})


def signout(request):
    if request.user.is_authenticated:
        logout(request)
    return redirect('accounts:home')

accounts/templates/accounts/home.html
{% extends 'accounts/layout.html' %}
{% block body %}
<h2 class="text-center">Welcome, <span style="color: green; font-weight: bold;">{{ request.user }}</span></h2>
{% endblock %}

accounts/templates/accounts/layout.html
<!DOCTYPE html>
<html lang="en" class="h-100">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'accounts/layout.css' %}">
    {% block static %}
    {% endblock %}
    <link rel="icon" type="image/x-icon" href="{% static 'accounts/logo.svg' %}">
    <title>Trading.com</title>
</head>

<body>
    <nav class="navbar navbar-expand-md navbar-light sticky-top" id="navbar">
        <div class="container">
            <a href="{% url 'accounts:home' %}" class="navbar-brand"><img src="{% static 'accounts/logo.svg' %}"
                    alt="logo" width="30" height="24" class="d-inline-block align-top"><span
                    style="color: green; font-weight: bold;">Trading</span>.com</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-bs-toggle="collapse"
                data-bs-target="#toggleMobileMenu" aria-controls="toggleMobileMenu" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="toggleMobileMenu">
                <ul class="navbar-nav ms-auto text-center">
                    <li><a class="nav-link" href="{% url 'accounts:home' %}">Home</a></li>
                    <li><a class="nav-link" href="{% url 'transactions:buy' %}">Buy</a></li>
                    <li><a class="nav-link" href="{% url 'transactions:sell' %}">Sell</a></li>
                    <li><a class="nav-link" href="#">Profile</a></li>
                    <li><a class="nav-link" href="{% url 'accounts:signout' %}">Logout</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container h-100">
        {% block body %}
        {% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
</body>

</html>

accounts/templates/accounts/signin.html
{% extends 'accounts/layout.html' %}
{% block body %}
<div class="container h-100">
    <div class="row h-100 justify-content-center align-items-center">
        <div class="col">
            {% for message in messages %}
            <div class="text-center alert alert-{{ message.tags }} alert-dismissible fade show">{{ message|safe }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            {% endfor %}
            <form method="POST">
                {% csrf_token %}
                {% load crispy_forms_tags %}
                {{ form|crispy }}
                <div class="mt-2 text-center">
                    <button type="submit" class="btn btn-outline-secondary">Sign in</button>
                </div>
            </form>
            <div class="link text-center mt-4">
                <a href="{% url 'accounts:signup' %}">Need an account?</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'accounts/layout.html' %}
{% block body %}
<div class="container h-100">
    <div class="row h-100 justify-content-center align-items-center">
        <div class="col">
            <form method="post">
                {% csrf_token %}
                {% load crispy_forms_tags %}
                {{ form|crispy }}
                <div class="mt-1 text-center">
                    <button type="submit" class="btn btn-outline-secondary">Signup</button>
                </div>
            </form>
            <div class="link text-center my-2">
                <a href="{% url 'accounts:signin' %}">Already have an account?</a>
            </div>
        </div>
    </div>
</div>
</div>
{% endblock %}